export const USER_GET_LOADING = "USER_GET_LOADING";
export const USER_GET_ERROR = "USER_GET_ERROR";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";

export const USER_GET_BY_ID_LOADING = "USER_GET_BY_ID_LOADING";
export const USER_GET_BY_ID_ERROR = "USER_GET_BY_ID_ERROR";
export const USER_GET_BY_ID_SUCCESS = "USER_GET_BY_ID_SUCCESS";

export const USER_POST_LOADING = "USER_POST_LOADING";
export const USER_POST_ERROR = "USER_POST_ERROR";
export const USER_POST_SUCCESS = "USER_POST_SUCCESS";

export const USER_UPDATE_LOADING = "USER_UPDATE_LOADING";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";

export const USER_UPLOAD_LOADING = "USER_UPLOAD_LOADING";
export const USER_UPLOAD_ERROR = "USER_UPLOAD_ERROR";
export const USER_UPLOAD_SUCCESS = "USER_UPLOAD_SUCCESS";

export const USER_SEND_LOADING = "USER_SEND_LOADING";
export const USER_SEND_ERROR = "USER_SEND_ERROR";
export const USER_SEND_SUCCESS = "USER_SEND_SUCCESS";