export const USER_AUTH_LOGIN_LOADING = "USER_AUTH_LOGIN_LOADING";
export const USER_AUTH_LOGIN_ERROR = "USER_AUTH_LOGIN_ERROR";
export const USER_AUTH_LOGIN_SUCCESS = "USER_AUTH_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";


export const ELECTRON_AUTH_LOGIN_LOADING = "ELECTRON_AUTH_LOGIN_LOADING";
export const ELECTRON_AUTH_LOGIN_ERROR = "ELECTRON_AUTH_LOGIN_ERROR";
export const ELECTRON_AUTH_LOGIN_SUCCESS = "ELECTRON_AUTH_LOGIN_SUCCESS";
export const ELECTRON_LOGOUT = "ELECTRON_LOGOUT";
