export const IndianStates = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
];
export const IndiaEducationBoards = [
    // National Education Boards
    "Central Board of Secondary Education (CBSE)",
    "Indian Certificate of Secondary Education (ICSE)",
    "National Institute of Open Schooling (NIOS)",
    "Council for the Indian School Certificate Examinations (CISCE)",

    // State Education Boards
    "Andhra Pradesh Board of Intermediate Education (APBIE)",
    "Assam Higher Secondary Education Council (AHSEC)",
    "Bihar School Examination Board (BSEB)",
    "Gujarat Secondary and Higher Secondary Education Board (GSEB)",
    "Haryana Board of School Education (HBSE)",
    "Himachal Pradesh Board of School Education (HPBOSE)",
    "Jharkhand Academic Council (JAC)",
    "Karnataka Secondary Education Examination Board (KSEEB)",
    "Kerala Board of Public Examinations (KBPE)",
    "Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)",
    "Madhya Pradesh Board of Secondary Education (MPBSE)",
    "Odisha Board of Secondary Education (BSE Odisha)",
    "Punjab School Education Board (PSEB)",
    "Rajasthan Board of Secondary Education (RBSE)",
    "Tamil Nadu State Board of School Examination (TN Board)",
    "Telangana State Board of Intermediate Education (TSBIE)",
    "Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP)",
    "West Bengal Board of Secondary Education (WBBSE)",
    "Others"
];
export const IndianQualifications = [
    "10th Standard",
    "12th Standard ",
    "Diploma",
    "Bachelor's Degree",
    "Master's Degree",
    "Doctorate (Ph.D.)",
    "Engineering Degree \n(B.Tech, B.E.)",
    "Medical Degree (MBBS)",
    "Law Degree (LLB)",
    "Chartered Accountancy (CA)",
    "Company Secretary (CS)",
    "Cost and Management\n Accountancy (CMA)",
    "Bachelor of Education\n (B.Ed.)",
    "Master of Business Administration (MBA)",
    "Master of Computer Applications (MCA)",
    "Bachelor of Science (B.Sc.)",
    "Bachelor of Arts (B.A.)",
    "Bachelor of Commerce (B.Com)",
    "Bachelor of Technology (B.Tech)",
    "Bachelor of Medicine",
    "Bachelor of Surgery (MBBS)",
    "Bachelor of Dental Surgery (BDS)",
    "Bachelor of Pharmacy (B.Pharm)",
    "Bachelor of Fine Arts (BFA)",
    "Bachelor of Business Administration (BBA)",
    "Master of Science (M.Sc.)",
    "Master of Arts (M.A.)",
    "Master of Commerce (M.Com)",
    "Master of Technology (M.Tech)",
    "Master of Medicine",
    "Master of Surgery (MD/MS)",
    "Doctor of Medicine (DM)",
    "Doctor of Surgery (DS)",
    "Pharmacy Doctorate (Pharm.D.)",
    "Doctor of Philosophy (Ph.D.)",
    "Others"
];
export const IndianSubjects = [
    "All Subjects",
    "Mathematics",
    "Science",
    "Physics",
    "Chemistry",
    "Biology",
    "History",
    "Geography",
    "Social Studies",
    "English",
    "Hindi",
    "Computer",
    "Physical Education",
    "Economics",
    "Sociology",
    "Psychology",
    "Accountancy",
    "Environmental Science",
    "Political Science",
    "Kannada",
    "Telugu",
    "Tamil",
    "Bengali",
    "Urdu",
    "Arabic",
];
export const IndianEducationLevels = [
    "Nursery",
    "LKG",
    "UKG",
    "1st",
    "2nd",
    "3rd",
    "4th",
    "5th",
    "6th",
    "7th",
    "8th",
    "9th",
    "10th",
    "11th",
    "12th",
    "College",
]
export const IndianMediums = [
    "English",
    "Hindi",
    "Bengali",
    "Telugu",
    "Marathi",
    "Tamil",
    "Urdu",
    "Gujarati",
    "Kannada",
    "Punjabi",
    "Malayalam",
    "Odia",
    "Assamese",
    "Konkani",
    "Manipuri",
    "Sindhi",
    "Nepali",
    "Others"
]
